try {
    hello();
} catch (error) {
    console.log(error);
}

try {
    anotherFunction();      
} catch (error) {
    console.log('Esto es un error')
}